fail_fast: true
repos:
  - repo: local
    hooks:
      - id: licence-present
        name: licence-present
        entry: SPDX-License-Identifier
        language: pygrep
        args: [--negate]
        files: "^(?!h5view/ui/).*\\.py$"
      - id: black
        name: black
        entry: venv/Scripts/black.exe
        language: system
        files: "^(?!h5view/ui/).*\\.py$"
      - id: isort
        name: isort (python)
        entry: venv/Scripts/isort.exe --settings-file pyproject.toml
        language: system
        files: "^(?!h5view/ui/).*\\.py$"
      - id: pylint
        name: pylint
        entry: venv/Scripts/pylint.exe
        language: system
        files: "^(?!h5view/ui/).*\\.py$"
      - id: mypy
        name: mypy
        entry: venv/Scripts/mypy.exe
        language: system
        files: "^(?!h5view/ui/).*\\.py$"
        require_serial: true
